Repository pingcap/failpoint, pull requests merged in 2019-04, with the labels that each got.

#1 failpoint: implement the basic logic of enable/disable and all statements rewrite
  MAINTAINERS.md
  Makefile
  code/expr_rewriter.go
  code/restorer.go
  code/rewriter.go
  code/rewriter_test.go
  failpoint-ctl/main.go
  failpoint-ctl/version/version.go
  failpoint.go
  go.mod
  http.go
  marker.go
  runtime.go
  terms.go
  terms_test.go
  tests/README.md
Labels: S:PTAL, feature

#6 code: fix default case in select statement rewrite
  code/rewriter.go
  code/rewriter_test.go
Labels: S:PTAL, bug

#7 failpoint: add unit test for WithHook
  failpoint_test.go
Labels: enhancement

#5 code: implement InjectContext marker function
  code/expr_rewriter.go
  code/rewriter_test.go
  marker.go
Labels: S:PTAL, feature

#9 code: fix assign case in select rewrite
  code/rewriter.go
  code/rewriter_test.go
Labels: S:PTAL, bug

#4 README: explain the failpoint usage and implementation details
  LICENSES/GOFAIL_LICENSE
  README.md
  media/rewrite-demo.png
Labels: enhancement

#8 code: auto extend failpoint name with package name
  code/expr_rewriter.go
  code/restorer.go
  code/rewriter.go
  code/rewriter_test.go
Labels: S:LGT1, feature

#12 *: add comment for exported elements
  code/restorer.go
  code/rewriter.go
  failpoint.go
  marker.go
  runtime.go
  terms.go
Labels: S:LGT1, enhancement

#14 code: add TypeSwitchStmt support in rewriter
  code/rewriter.go
  code/rewriter_test.go
Labels: S:LGT2, enhancement

#13 code: add unit test for restorer
  .codecov.yml
  code/rewriter_test.go
Labels: S:LGT1

#15 code: improve expr_rewriter test coverage
  code/expr_rewriter.go
  code/restorer_test.go
  code/rewriter_test.go
  http.go
  http_test.go
  runtime.go
  runtime_test.go
  terms_test.go
Labels: S:LGT2, enhancement

#17 code: refactor expression rewriter and support SendStmt and LabelStmt
  code/expr_rewriter.go
  code/rewriter.go
  code/rewriter_test.go
  failpoint-ctl/main.go
Labels: S:LGT2, enhancement

#16 tests: fix unit test
  Makefile
  code/rewriter.go
  code/rewriter_test.go
  failpoint_test.go
  http.go
  http_test.go
  runtime_test.go
Labels: S:LGT2, enhancement

#18 *: add comment to make linter happy
  Makefile
  failpoint-ctl/main.go
  failpoint-ctl/version/version.go
  failpoint.go
  http.go
  runtime_test.go
  terms.go
Labels: S:LGT2

#21 test: Add static check && adjust Travis-CI && make ineffassign happy
  .codecov.yml
  .travis.yml
  Makefile
  go.mod
  go.sum
  runtime_test.go
  tools/.gitkeep
Labels: enhancement

#19 code: add support for failpoint.Inject("failpoint-name", nil) and Return marker function
  README.md
  code/expr_rewriter.go
  code/rewriter_test.go
  marker.go
Labels: S:LGT2, feature

#20 code: improve rewriter test coverage
  code/rewriter.go
  code/rewriter_test.go
Labels: S:LGT1, contributor

#22 code: support rewrite ExprStmt Init in forStmt
  code/rewriter.go
  code/rewriter_test.go
Labels: S:LGT2

#23 code: add support for ast.IncDecStmt
  code/rewriter.go
  code/rewriter_test.go
  runtime_test.go
Labels: S:LGT2, feature

#24 code: support rewrite ExprStmt Init in IfStmt
  code/rewriter.go
  code/rewriter_test.go
Labels: S:LGT2

#26 runtime: fix return value sequence of failpoint.Eval
  failpoint.go
  failpoint_test.go
  runtime_test.go
Labels: bug

#27 code: optimize empty function generated code
  code/expr_rewriter.go
  code/rewriter_test.go
Labels: S:PTAL, enhancement
